#!/bin/bash -e
node ./node_modules/ace/lib/ace/anchor_test.js
node ./node_modules/ace/lib/ace/background_tokenizer_test.js
node ./node_modules/ace/lib/ace/commands/command_manager_test.js
node ./node_modules/ace/lib/ace/document_test.js
node ./node_modules/ace/lib/ace/edit_session_test.js
node ./node_modules/ace/lib/ace/editor_change_document_test.js
node ./node_modules/ace/lib/ace/editor_highlight_selected_word_test.js
node ./node_modules/ace/lib/ace/editor_navigation_test.js
node ./node_modules/ace/lib/ace/editor_text_edit_test.js
node ./node_modules/ace/lib/ace/ext/static_highlight_test.js
node ./node_modules/ace/lib/ace/layer/text_test.js
node ./node_modules/ace/lib/ace/lib/event_emitter_test.js
node ./node_modules/ace/lib/ace/mode/coffee/parser_test.js
node ./node_modules/ace/lib/ace/mode/coffee_highlight_rules_test.js
node ./node_modules/ace/lib/ace/mode/coldfusion_test.js
node ./node_modules/ace/lib/ace/mode/css_highlight_rules_test.js
node ./node_modules/ace/lib/ace/mode/css_test.js
node ./node_modules/ace/lib/ace/mode/css_worker_test.js
node ./node_modules/ace/lib/ace/mode/folding/cstyle_test.js
node ./node_modules/ace/lib/ace/mode/folding/html_test.js
node ./node_modules/ace/lib/ace/mode/folding/pythonic_test.js
node ./node_modules/ace/lib/ace/mode/folding/xml_test.js
node ./node_modules/ace/lib/ace/mode/html_highlight_rules_test.js
node ./node_modules/ace/lib/ace/mode/html_test.js
node ./node_modules/ace/lib/ace/mode/javascript_highlight_rules_test.js
node ./node_modules/ace/lib/ace/mode/javascript_test.js
node ./node_modules/ace/lib/ace/mode/javascript_worker_test.js
node ./node_modules/ace/lib/ace/mode/json_worker_test.js
node ./node_modules/ace/lib/ace/mode/liquid_highlight_rules_test.js
node ./node_modules/ace/lib/ace/mode/python_test.js
node ./node_modules/ace/lib/ace/mode/ruby_highlight_rules_test.js
node ./node_modules/ace/lib/ace/mode/text_test.js
node ./node_modules/ace/lib/ace/mode/xml_highlight_rules_test.js
node ./node_modules/ace/lib/ace/mode/xml_test.js
node ./node_modules/ace/lib/ace/placeholder_test.js
node ./node_modules/ace/lib/ace/range_list_test.js
node ./node_modules/ace/lib/ace/range_test.js
node ./node_modules/ace/lib/ace/search_test.js
node ./node_modules/ace/lib/ace/selection_test.js
node ./node_modules/ace/lib/ace/token_iterator_test.js
node ./node_modules/ace/lib/ace/virtual_renderer_test.js
node ./node_modules/apf/test/lm_test.js
node ./node_modules/jsDAV/node_modules/jsftp/lib/ftpParser_test.js
node ./node_modules/sinon/test/sinon/assert_test.js
node ./node_modules/sinon/test/sinon/collection_test.js
node ./node_modules/sinon/test/sinon/mock_test.js
node ./node_modules/sinon/test/sinon/sandbox_test.js
node ./node_modules/sinon/test/sinon/spy_test.js
node ./node_modules/sinon/test/sinon/stub_test.js
node ./node_modules/sinon/test/sinon/test_case_test.js
node ./node_modules/sinon/test/sinon/test_test.js
node ./node_modules/sinon/test/sinon/util/event_test.js
node ./node_modules/sinon/test/sinon/util/fake_server_test.js
node ./node_modules/sinon/test/sinon/util/fake_server_with_clock_test.js
node ./node_modules/sinon/test/sinon/util/fake_timers_test.js
node ./node_modules/sinon/test/sinon/util/fake_xml_http_request_test.js
node ./node_modules/sinon/test/sinon_test.js
node ./node_modules/socket.io/node_modules/redis/eval_test.js
node ./node_modules/socket.io/node_modules/redis/simple_test.js
node ./node_modules/socket.io/node_modules/redis/tests/reconnect_test.js
node ./node_modules/socket.io/node_modules/redis/tests/sub_quit_test.js
node ./node_modules/socket.io-client/node_modules/socket.io/node_modules/redis/eval_test.js
node ./node_modules/socket.io-client/node_modules/socket.io/node_modules/redis/simple_test.js
node ./node_modules/socket.io-client/node_modules/socket.io/node_modules/redis/tests/reconnect_test.js
node ./node_modules/socket.io-client/node_modules/socket.io/node_modules/redis/tests/sub_quit_test.js
node ./node_modules/treehugger/lib/treehugger/js/parse_test.js
node ./node_modules/treehugger/lib/treehugger/js/uglifyparser_test.js
node ./plugins-client/ext.codecomplete/local_completer_test.js
node ./plugins-client/ext.codecomplete/snippet_completer_test.js
node ./plugins-client/ext.colorpicker/colorpicker_test.js
node ./plugins-client/ext.console/logger_test.js
node ./plugins-client/ext.console/parser_test.js
node ./plugins-client/ext.gotofile/search_test.js
node ./plugins-client/ext.jslanguage/narcissus_jshint_test.js
node ./plugins-client/ext.jslanguage/outline_test.js
node ./plugins-client/ext.jslanguage/parse_test.js
node ./plugins-client/ext.jslanguage/scope_analyzer_test.js
node ./plugins-server/cloud9.ide.revisions/revisions_test.js
node ./plugins-server/cloud9.process-manager/process_manager_test.js
node ./plugins-server/cloud9.run.node-debug/node_debug_test.js
node ./plugins-server/cloud9.run.shell/shell_test.js
